### ISSUE TITLE
Error downloading object

### ISSUE THREAD

**Issue by ghost** [Warmduscher/arkham-horror-octgn-image-packs-german#1]
Hi @Warmduscher, ich wollte das Repository clonen. Leider bekomme ich dabei eine Fehlermeldung:

Error downloading object: o8c/COR01 - Grundspiel.o8c (23aa45d): Smudge error: Error downloading o8c/COR01 - Grundspiel.o8c (23aa45d0f95183d210e9605154dfc55b0aeec485c0d4f2a3d30bbb6b9de0b65d): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Gibt es eine Möglichkeit, die .o8c-Dateien bereitzustellen oder die Fehlermeldugn anderweitig zu lösen? Ich würde mich freuen, wenn ich deine tolle Arbeit hier für ein paar Spiel mit OCTGN  nutzen könnte.

Vielen Dank

**Comment by Warmduscher** [comment]
Hi,

ja Github hat ein Quota für die kostenfreien Repos eingeführt und für große binäre Dateiobjekte zusätzlich auf LFS umgestellt. Das sorgt für Probleme mit dem Repo. Ich fürchte ich müsste die Files auf einen anderen Storage pumpen. Ich habe hier mal eine Kopie meiner Image-Database eingestellt: 

https://mega.nz/folder/jERTgDzL#LiKbIIkEYAjuiLHcozg8OQ 

Die .o8c Pakete sind von mir schon ein paar Jahre nicht mehr aktualisiert worden.

**Comment by ghost** [comment]
Super und vielen lieben Dank. Werde ich mir bei Gelegenheit mal ansehen.
